repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        exclude: ^tests/fixtures/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'PYTHONPATH=. pylint --rcfile=pyproject.toml "$@"'
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: ["pylint", "pytest"]
        exclude: ^plugins/modules/

      - id: pylint
        name: pylint-modules
        entry: bash -c 'PYTHONPATH=. pylint --rcfile=plugins/modules/.pylintrc plugins/modules'
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: ["pylint", "pytest"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: bash -c 'PYTHONPATH=. pytest --cov=plugins --cov-report=term-missing'
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
        always_run: true
        stages: [pre-commit]
