namespace: ibiscardigan
name: multipass
version: 0.1.0
readme: README.md
authors:
  - HLSM
description: An Ansible collection for managing Multipass VMs.
license: MIT
tags: [multipass, vm, virtualization, ansible]
dependencies: {}
repository: https://github.com/ibiscardigan/ansible_multipass
homepage: https://github.com/ibiscardigan/ansible_multipass
issues: https://github.com/ibiscardigan/ansible_multipass/issues
