name: Auto Tag and Release

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: pip install ansible-core

      - name: Extract version from galaxy.yml
        id: extract_version
        run: |
          VERSION=$(grep '^version:' ibiscardigan/multipass/galaxy.yml | awk '{ print $2 }')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          VERSION=${{ steps.extract_version.outputs.version }}
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Build collection
        working-directory: ibiscardigan/multipass
        run: |
          ansible-galaxy collection build --output-path dist
          echo "TARFILE=$(ls dist/*.tar.gz)" >> $GITHUB_ENV

      - name: Create GitHub release
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: Release v${{ steps.extract_version.outputs.version }}
          files: ${{ env.TARFILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
